### ISSUE TITLE
React - Barcode scanner functionality not working

### ISSUE THREAD

**Issue by ntehclsupport** [HCL-TECH-SOFTWARE/commerce-react-barcode-scanner-asset#3]
Hi Innovation Team,

When we developed the barcode scanner functionality, we followed the directions from HCL that had shared with us in the React Barcode Asset, described in https://github.com/HCL-TECH-SOFTWARE/commerce-react-barcode-scanner-asset.

However, when downloading the mentioned "react-webcam-barcode-scanner" npm package, its page clearly said it had been deprecated and that we should use the "react-qr-barcode-scanner" instead, which was built on top of the original "react-webcam-barcode-scanner" plugin. So that's what we did and the plugin seemed to work fine with the sample bar codes we had at the development time.

However, during the UAT when actual barcodes were used the plugin demonstrated to not be able to *focus* the camera on small barcodes. So, they can't be read. Only barcodes with a minimum size can be read by this plugin and this doesn't fulfill clients needs.

We couldn't find any config in the plugin that could fix this issue, so we're looking for some recommendations on how to fix and/or workaround this problem.

Regards,

Mateus.

**Comment by SanjeevKGoyal** [comment]
Hi Mateus,
Which HCLC version you are using this asset on?

We have a new version of these asset which works with 9.1.10.0+.  It is expected to be available on GitHub in few days.

W.r.t. barcode size issue, can you share a screenshot of the barcode you are trying to scan?

Thanks,
Sanjeev

**Comment by ntehclsupport** [comment]
Hi HCL,

We’re using HCL Commerce v. 9.1.7 for the transaction server and v9.1.8 for the search.

Related to sample barcodes, that’s the point: sharing screenshots does not help because usually the barcode on the computer’s screen is big enough to be read by the plugin. 

However, if you try to read a real barcode from a real product, in particular when it’s small, that’s when you will see the issue. The plugin can’t focus on the barcode so it can’t read it. In one of my tests I tried to read the barcode from a ½ gallon recipient of milk or from a headset package I purchased. No luck. Anything medium to small can’t be read. Tests were successful only when the barcode was big on my computer’s scree, but that’s not the real world. 

Regards.

**Comment by SanjeevKGoyal** [comment]
As mentioned in the asset documentation, this asset relies on a particular barcode library, and based on that it's working as expected. You are free to use any other barcode library if that helps your product-scanning better.

We have recently published new version of this asset which works with 9.1.10.
